language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xcodebuild -showsdks
  - xctool -project VolumeBar/VolumeBar.xcodeproj -scheme VolumeBar -sdk iphonesimulator9.2 build analyze

